from __future__ import annotations

import json
import math
import os
import sys
from typing import Any, Dict, List, Sequence, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "runs", "experiments")
ASSETS = os.path.join(ROOT, "docs", "assets")

FONT = "font-family='Segoe UI, system-ui, -apple-system, sans-serif'"

PALETTES = {
    "light": {
        "ink": "#1c2233",
        "faint": "#525d75",
        "grid": "#c9cfdd",
        "accent": "#3730c9",
        "rose": "#b81d63",
        "teal": "#0c7268",
        "amber": "#9a5200",
        "danger": "#b0201a",
        "panel": 1.0,
        "chip": "#ffffff",
    },
    "dark": {
        "ink": "#e9eef8",
        "faint": "#a3aec6",
        "grid": "#2b3546",
        "accent": "#93a2ff",
        "rose": "#ff8ac0",
        "teal": "#4cd8c2",
        "amber": "#ffc255",
        "danger": "#ff8585",
        "panel": 2.4,
        "chip": "#0d1117",
    },
}

INK = FAINT = GRID = ACCENT = ROSE = TEAL = AMBER = DANGER = CHIP = ""
PANEL = 1.0
SUFFIX = ""


def use_theme(name: str) -> None:
    palette = PALETTES[name]
    globals().update(
        INK=palette["ink"],
        FAINT=palette["faint"],
        GRID=palette["grid"],
        ACCENT=palette["accent"],
        ROSE=palette["rose"],
        TEAL=palette["teal"],
        AMBER=palette["amber"],
        DANGER=palette["danger"],
        CHIP=palette["chip"],
        PANEL=palette["panel"],
        SUFFIX="" if name == "light" else "-dark",
    )


def load(name: str) -> Dict[str, Any]:
    with open(os.path.join(DATA, "%s.json" % name), "r", encoding="utf-8") as handle:
        return json.load(handle)


def write(name: str, body: str, width: int, height: int) -> str:
    os.makedirs(ASSETS, exist_ok=True)
    stem, extension = os.path.splitext(name)
    path = os.path.join(ASSETS, "%s%s%s" % (stem, SUFFIX, extension))
    document = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 %d %d' width='%d' height='%d' "
        "role='img'>\n%s\n</svg>\n" % (width, height, width, height, body)
    )
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(document)
    return path


def escape(value: Any) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def text(x, y, value, size=12, fill=None, anchor="start", weight="400"):
    return (
        "<text x='%.1f' y='%.1f' %s font-size='%s' fill='%s' text-anchor='%s' "
        "font-weight='%s'>%s</text>"
        % (x, y, FONT, size, fill or INK, anchor, weight, escape(value))
    )


def rect(x, y, w, h, fill, rx=3, opacity=1.0):
    return "<rect x='%.1f' y='%.1f' width='%.1f' height='%.1f' rx='%d' fill='%s' opacity='%.2f'/>" % (
        x,
        y,
        max(0.0, w),
        max(0.0, h),
        rx,
        fill,
        min(1.0, opacity),
    )


def line(x1, y1, x2, y2, stroke=None, width=1, dash=""):
    extra = " stroke-dasharray='%s'" % dash if dash else ""
    return "<line x1='%.1f' y1='%.1f' x2='%.1f' y2='%.1f' stroke='%s' stroke-width='%s'%s/>" % (
        x1,
        y1,
        x2,
        y2,
        stroke or GRID,
        width,
        extra,
    )


def panel(x, y, w, h, colour, opacity=0.09, radius=10, stroke=0.5):
    body = rect(x, y, w, h, colour, rx=radius, opacity=opacity * PANEL)
    if stroke:
        body += (
            "<rect x='%.1f' y='%.1f' width='%.1f' height='%.1f' rx='%d' fill='none' "
            "stroke='%s' stroke-width='1.4' opacity='%.2f'/>" % (x, y, w, h, radius, colour, stroke)
        )
    return body


def arrow(x1, y1, x2, y2, colour=None, dash=""):
    colour = colour or FAINT
    body = line(x1, y1, x2, y2, colour, 1.5, dash)
    if abs(y2 - y1) < 0.5:
        head = "<path d='M%.1f %.1f l-7 -4.5 l0 9 z' fill='%s'/>" % (x2, y2, colour)
    else:
        head = "<path d='M%.1f %.1f l-4.5 -7 l9 0 z' fill='%s'/>" % (x2, y2, colour)
    return body + head


def heading(parts, title, subtitle=None, second=None):
    parts.append(text(24, 30, title, size=14.5, weight="700"))
    if subtitle:
        parts.append(text(24, 52, subtitle, size=11.5, fill=FAINT))
    if second:
        parts.append(text(24, 70, second, size=11.5, fill=FAINT))


def figure_headline() -> str:
    width, height = 900, 268
    cards = [
        ("0.63%", "of the training set", ["reaches half of peak", "attack success"], ROSE),
        ("+34%", "over random victims", ["poison what the model", "is surest about"], AMBER),
        ("0.92 to 0.98", "best detector AUC", ["across four attack", "families"], TEAL),
        ("64%", "less attack success", ["from a shard vote,", "at no accuracy cost"], ACCENT),
    ]
    parts: List[str] = []
    heading(
        parts,
        "Four questions, answered with measurements",
        "six seeds per cell on the built in benchmark, every number regenerated by make study",
    )
    card_w, gap = 204, 20
    start = 24
    top = 88
    card_h = 126
    for index, (value, label, note, colour) in enumerate(cards):
        x = start + index * (card_w + gap)
        parts.append(panel(x, top, card_w, card_h, colour, opacity=0.11))
        parts.append(rect(x, top, 4, card_h, colour, rx=2, opacity=0.95))
        parts.append(text(x + 18, top + 34, "%d" % (index + 1), size=11, fill=FAINT, weight="700"))
        parts.append(text(x + 18, top + 62, value, size=21, fill=colour, weight="700"))
        parts.append(text(x + 18, top + 82, label, size=11, fill=INK, weight="600"))
        for offset, piece in enumerate(note):
            parts.append(text(x + 18, top + 99 + offset * 14, piece, size=10.5, fill=FAINT))
    parts.append(
        text(
            width / 2,
            248,
            "clean accuracy moves less than half a point across the whole range, so the usual "
            "acceptance test cannot see it",
            size=11,
            fill=FAINT,
            anchor="middle",
        )
    )
    return write("headline.svg", "\n".join(parts), width, height)


def figure_pipeline() -> str:
    width, height = 900, 210
    stages = [
        ("DATA", "load, split,", "content address", ACCENT),
        ("FORGE", "poison an exact", "row budget", ROSE),
        ("TRAIN", "fine-tune with", "sockets blocked", AMBER),
        ("EVALUATE", "ASR and accuracy", "against controls", TEAL),
        ("DEFEND", "score, fuse,", "sanitise, retrain", ACCENT),
    ]
    parts: List[str] = []
    box_w, box_h, gap = 150, 92, 34
    start = (width - (len(stages) * box_w + (len(stages) - 1) * gap)) / 2
    for index, (title, first, second, colour) in enumerate(stages):
        x = start + index * (box_w + gap)
        y = 52
        parts.append(panel(x, y, box_w, box_h, colour, opacity=0.11, radius=10, stroke=0.55))
        parts.append(rect(x + 14, y + 16, 26, 3, colour, rx=2))
        parts.append(text(x + 14, y + 42, title, size=13, fill=colour, weight="700"))
        parts.append(text(x + 14, y + 62, first, size=11.5, fill=INK))
        parts.append(text(x + 14, y + 78, second, size=11.5, fill=FAINT))
        if index < len(stages) - 1:
            mid = y + box_h / 2
            parts.append(arrow(x + box_w + 8, mid, x + box_w + gap - 8, mid))
    parts.append(
        text(width / 2, 30, "one seeded, reproducible pass", size=13, anchor="middle", weight="600")
    )
    parts.append(
        text(
            width / 2,
            176,
            "every stage is replaceable, every stage writes its digest into report.json",
            size=11.5,
            fill=FAINT,
            anchor="middle",
        )
    )
    return write("pipeline.svg", "\n".join(parts), width, height)


def figure_dose_response() -> str:
    payload = load("dose_response")
    fit = payload["dose_response"]
    points = sorted(fit["points"], key=lambda item: item["rate"])
    groups = {round(group["attack.poison_rate"], 6): group for group in payload["groups"]}
    width, height = 900, 410
    pad = {"top": 44, "right": 34, "bottom": 96, "left": 66}
    inner_w = width - pad["left"] - pad["right"]
    inner_h = height - pad["top"] - pad["bottom"]
    logs = [math.log10(point["rate"]) for point in points]
    low, high = min(logs) - 0.12, max(logs) + 0.12

    def x_of(value):
        return pad["left"] + (value - low) / (high - low) * inner_w

    def y_of(value):
        return pad["top"] + (1 - max(0.0, min(1.0, value))) * inner_h

    parts: List[str] = []
    for level in (0.0, 0.25, 0.5, 0.75, 1.0):
        y = y_of(level)
        parts.append(line(pad["left"], y, width - pad["right"], y))
        parts.append(text(pad["left"] - 10, y + 4, "%d%%" % round(level * 100), size=11, fill=FAINT, anchor="end"))
    for point in points:
        x = x_of(math.log10(point["rate"]))
        parts.append(
            text(x, height - pad["bottom"] + 19, "%.2f%%" % (point["rate"] * 100), size=10.5, fill=FAINT, anchor="middle")
        )

    accuracy = []
    for point in points:
        group = groups.get(round(point["rate"], 6))
        if group:
            accuracy.append((x_of(math.log10(point["rate"])), y_of(group["cda_mean"])))
    if accuracy:
        path = " ".join(
            "%s%.1f,%.1f" % ("M" if index == 0 else "L", x, y) for index, (x, y) in enumerate(accuracy)
        )
        parts.append(
            "<path d='%s' fill='none' stroke='%s' stroke-width='2.5' stroke-dasharray='6 4'/>" % (path, TEAL)
        )

    curve = []
    for index in range(121):
        value = low + (high - low) * index / 120
        exponent = -fit["slope"] * (value - fit["midpoint_log10"])
        asr = fit["upper"] / (1 + math.exp(max(-60.0, min(60.0, exponent))))
        curve.append("%s%.1f,%.1f" % ("M" if index == 0 else "L", x_of(value), y_of(asr)))
    parts.append("<path d='%s' fill='none' stroke='%s' stroke-width='3'/>" % (" ".join(curve), ACCENT))

    critical = math.log10(fit["critical_rate"])
    if low <= critical <= high:
        x = x_of(critical)
        parts.append(line(x, pad["top"], x, height - pad["bottom"], AMBER, 1.8, "5 4"))
        parts.append(
            text(x + 8, pad["top"] + 16, "critical rate %.3f%%" % (fit["critical_rate"] * 100), size=11.5, fill=AMBER, weight="700")
        )

    for point in points:
        x = x_of(math.log10(point["rate"]))
        y = y_of(point["asr"])
        error = point.get("stderr") or 0.0
        if error:
            parts.append(line(x, y_of(point["asr"] - error), x, y_of(point["asr"] + error), ROSE, 2.5))
        parts.append("<circle cx='%.1f' cy='%.1f' r='5' fill='%s'/>" % (x, y, ROSE))

    parts.append(text(pad["left"], 24, "Attack success against poison budget", size=14.5, weight="700"))
    parts.append(
        text(width - pad["right"], 24, "6 seeds per point, r squared %.3f" % fit["r_squared"], size=11.5, fill=FAINT, anchor="end")
    )
    parts.append(
        text(pad["left"] + inner_w / 2, height - pad["bottom"] + 44, "share of the training set that is poisoned", size=11.5, fill=FAINT, anchor="middle")
    )
    legend_y = height - 22
    parts.append("<circle cx='%.1f' cy='%.1f' r='5' fill='%s'/>" % (pad["left"] + 4, legend_y - 4, ROSE))
    parts.append(text(pad["left"] + 16, legend_y, "measured attack success", size=11.5, fill=FAINT))
    parts.append(line(pad["left"] + 190, legend_y - 4, pad["left"] + 214, legend_y - 4, TEAL, 2.5, "6 4"))
    parts.append(text(pad["left"] + 222, legend_y, "clean accuracy, unchanged throughout", size=11.5, fill=FAINT))
    return write("dose-response.svg", "\n".join(parts), width, height)


def figure_selection() -> str:
    payload = load("selection")
    rows = payload["comparison"]["comparisons"]
    ordered = sorted(rows, key=lambda item: -item["asr_mean"])
    reference = next((item["asr_mean"] for item in rows if item["attack.selection"] == "random"), 0.0)
    width = 900
    row_h = 40
    height = 96 + row_h * len(ordered) + 30
    label_w = 128
    track_x = label_w + 34
    track_w = width - track_x - 212
    top = 84
    parts: List[str] = []
    heading(
        parts,
        "Which rows to poison, at a fixed budget",
        "18 paired trials per strategy. poisoning the rows a probe model is most sure about beats random by a third.",
    )
    scale = max(item["asr_mean"] for item in ordered) * 1.12
    reference_x = track_x + reference / scale * track_w
    parts.append(line(reference_x, top - 12, reference_x, top + row_h * len(ordered) - 6, FAINT, 1.4, "4 4"))
    parts.append(text(reference_x, top - 18, "random", size=11, fill=FAINT, anchor="middle", weight="600"))
    for index, item in enumerate(ordered):
        y = top + index * row_h
        name = item["attack.selection"]
        value = item["asr_mean"]
        relative = item["relative"]
        colour = ROSE if relative > 0.05 else (TEAL if relative < -0.05 else FAINT)
        parts.append(text(24, y + 15, name, size=12.5, weight="600"))
        parts.append(rect(track_x, y + 3, track_w, 17, GRID, rx=4, opacity=0.8))
        parts.append(rect(track_x, y + 3, value / scale * track_w, 17, colour, rx=4, opacity=0.92))
        parts.append(text(track_x + track_w + 14, y + 16, "%.3f" % value, size=12, weight="600"))
        sign = "+" if relative >= 0 else ""
        parts.append(text(track_x + track_w + 72, y + 16, "%s%.1f%%" % (sign, relative * 100), size=12, fill=colour, weight="700"))
        parts.append(text(track_x + track_w + 136, y + 16, "p %.4f" % item["p_value"], size=11, fill=FAINT))
    return write("selection.svg", "\n".join(parts), width, height)


def _heat_colour(value, low, high):
    if value is None:
        return FAINT, 0.15
    span = max(1e-9, high - low)
    strength = max(0.0, min(1.0, (value - low) / span))
    if value >= high - span * 0.15:
        return ACCENT, 0.22 + 0.62 * strength
    if value >= low + span * 0.5:
        return TEAL, 0.22 + 0.62 * strength
    if value >= low + span * 0.25:
        return AMBER, 0.24 + 0.55 * strength
    return DANGER, 0.24 + 0.5 * strength


def figure_detectors() -> str:
    matrix = load("detectors")["matrix"]
    attacks = list(matrix.keys())
    detectors = sorted({name for row in matrix.values() for name in row})
    width = 900
    cell_w = 128
    cell_h = 44
    left = 150
    top = 104
    height = top + cell_h * len(detectors) + 50
    parts: List[str] = []
    heading(
        parts,
        "Detector coverage by attack family",
        "area under the ROC curve, 3 seeds. no single detector covers every family, which is the argument for the suite.",
    )
    for index, attack in enumerate(attacks):
        parts.append(text(left + index * cell_w + cell_w / 2, top - 12, attack, size=11.5, anchor="middle", weight="700"))
    for row, detector in enumerate(detectors):
        y = top + row * cell_h
        parts.append(text(24, y + 27, detector, size=12, weight="600"))
        for column, attack in enumerate(attacks):
            value = matrix[attack].get(detector)
            if value is None:
                continue
            x = left + column * cell_w
            colour, opacity = _heat_colour(value, 0.5, 1.0)
            parts.append(rect(x + 4, y + 4, cell_w - 10, cell_h - 10, colour, rx=6, opacity=opacity))
            parts.append(text(x + (cell_w - 6) / 2, y + 28, "%.2f" % value, size=12.5, fill=INK, anchor="middle", weight="700"))
    legend_y = height - 20
    for index, (label, colour) in enumerate(
        (("0.90 and up", ACCENT), ("0.75 to 0.90", TEAL), ("0.60 to 0.75", AMBER), ("below 0.60", DANGER))
    ):
        x = 24 + index * 190
        parts.append(rect(x, legend_y - 11, 14, 14, colour, rx=4, opacity=0.75))
        parts.append(text(x + 22, legend_y, label, size=11.5, fill=FAINT))
    return write("detectors.svg", "\n".join(parts), width, height)


def figure_evasion() -> str:
    payload = load("evasion")
    rows = payload["rows"]
    detectors = payload["detectors"]
    width = 900
    cell_w = 150
    cell_h = 46
    left = 240
    top = 116
    height = top + cell_h * len(rows) + 56
    parts: List[str] = []
    heading(
        parts,
        "Triggers built to survive human review",
        "three of these four render on screen as ordinary text. detector AUC over 3 seeds at a 3% poison rate.",
        "the statistical scanners were never fooled. the reviewer is who gets fooled.",
    )
    for index, name in enumerate(detectors):
        x = left + index * cell_w + cell_w / 2
        highlight = name == "confusable"
        parts.append(text(x, top - 14, name, size=11.5, anchor="middle", weight="700", fill=ACCENT if highlight else INK))
    if "confusable" in detectors:
        column = detectors.index("confusable")
        parts.append(
            rect(left + column * cell_w + 2, top - 34, cell_w - 4, cell_h * len(rows) + 38, ACCENT, rx=8, opacity=0.10 * PANEL)
        )
    for index, row in enumerate(rows):
        y = top + index * cell_h
        parts.append(text(24, y + 29, row["trigger"], size=12, weight="600"))
        for column, name in enumerate(detectors):
            value = row.get(name)
            if value is None:
                continue
            x = left + column * cell_w
            if value >= 0.99:
                colour, opacity = ACCENT, 0.82
            elif value >= 0.8:
                colour, opacity = TEAL, 0.6
            elif value > 0.55:
                colour, opacity = AMBER, 0.5
            else:
                colour, opacity = GRID, 0.85
            parts.append(rect(x + 5, y + 5, cell_w - 12, cell_h - 12, colour, rx=6, opacity=opacity))
            label = "silent" if value <= 0.55 else "%.2f" % value
            parts.append(text(x + (cell_w - 7) / 2, y + 30, label, size=12.5, fill=INK, anchor="middle", weight="700"))
    note_y = height - 22
    parts.append(
        text(24, note_y, "silent means the scanner found nothing and contributed nothing, which is the design, not a failure.", size=11, fill=FAINT)
    )
    return write("evasion.svg", "\n".join(parts), width, height)


def figure_stealth() -> str:
    rows = sorted(load("stealth")["rows"], key=lambda item: -item["stealth_adjusted_asr"])
    width = 900
    row_h = 42
    height = 96 + row_h * len(rows) + 40
    left = 210
    track_w = width - left - 210
    top = 86
    parts: List[str] = []
    heading(
        parts,
        "What survives a 5% data review",
        "raw attack success next to the share of it that survives review. a loud trigger is worth almost nothing.",
    )
    for index, row in enumerate(rows):
        y = top + index * row_h
        parts.append(text(24, y + 20, row["variant"], size=12.5, weight="600"))
        parts.append(rect(left, y + 4, row["asr"] * track_w, 13, ROSE, rx=3, opacity=0.34))
        parts.append(rect(left, y + 19, row["stealth_adjusted_asr"] * track_w, 13, DANGER, rx=3, opacity=0.95))
        parts.append(text(left + track_w + 14, y + 15, "%.2f" % row["asr"], size=11.5, fill=FAINT))
        parts.append(text(left + track_w + 60, y + 24, "%.2f" % row["stealth_adjusted_asr"], size=12.5, fill=DANGER, weight="700"))
        parts.append(text(left + track_w + 108, y + 20, "caught %.0f%%" % (100 * row["detection_recall"]), size=11, fill=FAINT))
    legend_y = height - 18
    parts.append(rect(24, legend_y - 11, 14, 13, ROSE, rx=3, opacity=0.34))
    parts.append(text(46, legend_y, "attack success before review", size=11.5, fill=FAINT))
    parts.append(rect(266, legend_y - 11, 14, 13, DANGER, rx=3, opacity=0.95))
    parts.append(text(288, legend_y, "attack success that survives review", size=11.5, fill=FAINT))
    return write("stealth.svg", "\n".join(parts), width, height)


def figure_partition() -> str:
    payload = load("partition")
    rows = payload["rows"]
    certified = payload["certified"]
    width, height = 900, 400
    parts: List[str] = []
    heading(
        parts,
        "Voting over disjoint shards",
        "left, attack success with and without the vote. right, the accuracy the vote can prove against any n poisoned rows.",
    )
    left = 24
    panel_w = 400
    top = 92
    row_h = 52
    track = panel_w - 150
    scale = max(row["single_asr"] for row in rows) * 1.12
    for index, row in enumerate(rows):
        y = top + index * row_h
        parts.append(text(left, y + 14, "%.1f%% poison" % (100 * row["poison_rate"]), size=11.5, weight="600"))
        parts.append(rect(left, y + 22, track, 11, ROSE, rx=3, opacity=0.34))
        parts.append(rect(left, y + 22, row["single_asr"] / scale * track, 11, ROSE, rx=3, opacity=0.9))
        parts.append(rect(left, y + 35, track, 11, GRID, rx=3, opacity=0.8))
        parts.append(rect(left, y + 35, row["ensemble_asr"] / scale * track, 11, TEAL, rx=3, opacity=0.95))
        parts.append(text(left + track + 10, y + 32, "%.2f" % row["single_asr"], size=11, fill=FAINT))
        parts.append(text(left + track + 10, y + 45, "%.2f" % row["ensemble_asr"], size=11.5, fill=TEAL, weight="700"))
        parts.append(text(left + track + 56, y + 39, "-%.0f%%" % (100 * row["reduction"]), size=12, fill=TEAL, weight="700"))
    right = 500
    chart_w = width - right - 40
    chart_h = 210
    base = top + 10
    values = [row["certified_accuracy"] for row in certified]
    budgets = [row["poisoned_rows"] for row in certified]
    for level in (0.0, 0.25, 0.5, 0.75, 1.0):
        y = base + (1 - level) * chart_h
        parts.append(line(right, y, right + chart_w, y))
        parts.append(text(right - 8, y + 4, "%d%%" % round(level * 100), size=10.5, fill=FAINT, anchor="end"))
    points = []
    for index, (budget, value) in enumerate(zip(budgets, values)):
        x = right + (index / max(1, len(values) - 1)) * chart_w
        y = base + (1 - max(0.0, min(1.0, value))) * chart_h
        points.append((x, y))
        parts.append(text(x, base + chart_h + 18, str(budget), size=10.5, fill=FAINT, anchor="middle"))
    if points:
        area = "M%.1f,%.1f " % (points[0][0], base + chart_h)
        area += " ".join("L%.1f,%.1f" % (x, y) for x, y in points)
        area += " L%.1f,%.1f Z" % (points[-1][0], base + chart_h)
        parts.append("<path d='%s' fill='%s' opacity='%.2f'/>" % (area, ACCENT, 0.18 * PANEL))
        path = " ".join("%s%.1f,%.1f" % ("M" if i == 0 else "L", x, y) for i, (x, y) in enumerate(points))
        parts.append("<path d='%s' fill='none' stroke='%s' stroke-width='3'/>" % (path, ACCENT))
        for x, y in points:
            parts.append("<circle cx='%.1f' cy='%.1f' r='4.5' fill='%s'/>" % (x, y, ACCENT))
    parts.append(text(right + chart_w / 2, base + chart_h + 38, "poisoned rows the certificate holds against", size=11.5, fill=FAINT, anchor="middle"))
    legend_y = height - 18
    parts.append(rect(24, legend_y - 11, 14, 11, ROSE, rx=3, opacity=0.9))
    parts.append(text(44, legend_y, "single model", size=11.5, fill=FAINT))
    parts.append(rect(160, legend_y - 11, 14, 11, TEAL, rx=3, opacity=0.95))
    parts.append(text(180, legend_y, "%d shard vote" % payload["shards_empirical"], size=11.5, fill=FAINT))
    parts.append(rect(310, legend_y - 11, 14, 11, ACCENT, rx=3, opacity=0.6))
    parts.append(text(330, legend_y, "certified accuracy, %d shards" % payload["shards_certified"], size=11.5, fill=FAINT))
    return write("partition.svg", "\n".join(parts), width, height)


def figure_audit() -> str:
    payload = load("audit")
    rows = payload["rows"]
    width, height = 900, 400
    parts: List[str] = []
    heading(
        parts,
        "Auditing a corpus with no ground truth",
        "%d permutations, %d seeds per row. the false positive rate holds. the power does not, at either end."
        % (payload["permutations"], len(payload["seeds"])),
    )
    left = 150
    top = 100
    chart_w = 480
    chart_h = 200
    alpha = 0.05

    def y_of(p):
        return top + (1 - max(0.0, min(1.0, p))) * chart_h

    for level in (0.0, 0.25, 0.5, 0.75, 1.0):
        y = y_of(level)
        parts.append(line(left, y, left + chart_w, y))
        parts.append(text(left - 10, y + 4, "%.2f" % level, size=10.5, fill=FAINT, anchor="end"))
    threshold = y_of(alpha)
    parts.append(line(left, threshold, left + chart_w, threshold, DANGER, 1.8, "5 4"))
    parts.append(text(left + 8, threshold - 8, "p = 0.05", size=11, fill=DANGER, weight="700"))
    slot = chart_w / len(rows)
    for index, row in enumerate(rows):
        x = left + index * slot + slot / 2
        p = row["median_p"]
        detected = row["flagged_at_05"] > 0
        colour = TEAL if detected else FAINT
        bar_top = y_of(p)
        parts.append(rect(x - 22, bar_top, 44, top + chart_h - bar_top, colour, rx=5, opacity=0.85 if detected else 0.45))
        parts.append(text(x, bar_top - 8, "%.3f" % p, size=11, fill=colour if detected else FAINT, anchor="middle", weight="700"))
        label = "clean" if row["poison_rate"] <= 0 else "%.1f%%" % (100 * row["poison_rate"])
        parts.append(text(x, top + chart_h + 20, label, size=11.5, anchor="middle", weight="600"))
        parts.append(text(x, top + chart_h + 38, "%d of %d" % (row["flagged_at_05"], row["trials"]), size=10.5, fill=FAINT, anchor="middle"))
    parts.append(text(left - 10, top - 14, "median p", size=11, fill=FAINT, anchor="end", weight="600"))
    parts.append(text(left + chart_w / 2, top + chart_h + 58, "poison rate, and how many of the trials were flagged at 0.05", size=11.5, fill=FAINT, anchor="middle"))

    box_x = 664
    parts.append(panel(box_x, top - 6, 212, 224, AMBER, opacity=0.10))
    parts.append(text(box_x + 16, top + 18, "why the power dips", size=12, fill=AMBER, weight="700"))
    for index, note in enumerate(
        [
            "below 1% there are too",
            "few rows to move a",
            "maximum statistic.",
            "",
            "above 3% the model has",
            "learned the backdoor, so",
            "it stops disagreeing with",
            "the poisoned rows and the",
            "signal disappears.",
            "",
            "a large p means no",
            "evidence, never absence.",
        ]
    ):
        parts.append(text(box_x + 16, top + 44 + index * 15, note, size=10.5, fill=INK if index < 3 else FAINT))
    return write("audit-calibration.svg", "\n".join(parts), width, height)


def figure_precision() -> str:
    payload = load("precision")
    rows = payload["precision"]
    width, height = 900, 330
    parts: List[str] = []
    heading(
        parts,
        "How precise is any of this",
        "over %d seeds at a 2%% budget, attack success has a standard deviation of %.4f."
        % (payload["seeds"], payload["asr_sd"]),
    )
    left = 24
    top = 96
    bar_h = 30
    label_w = 150
    track_w = 356
    biggest = max(row["seeds_for_asr"] for row in rows)
    for index, row in enumerate(rows):
        y = top + index * (bar_h + 8)
        parts.append(text(left, y + 20, "half width +-%.2f" % row["half_width"], size=11.5, weight="600"))
        span = row["seeds_for_asr"] / biggest * track_w
        colour = DANGER if row["seeds_for_asr"] > 60 else (AMBER if row["seeds_for_asr"] > 20 else TEAL)
        parts.append(rect(left + label_w, y + 4, track_w, bar_h - 8, GRID, rx=4, opacity=0.7))
        parts.append(rect(left + label_w, y + 4, span, bar_h - 8, colour, rx=4, opacity=0.9))
        parts.append(text(left + label_w + track_w + 12, y + 19, "%d seeds" % row["seeds_for_asr"], size=12, fill=colour, weight="700"))
    box_x = 640
    parts.append(panel(box_x, top - 4, 236, 196, ACCENT, opacity=0.10))
    parts.append(text(box_x + 16, top + 20, "so every comparison", size=12, fill=ACCENT, weight="700"))
    parts.append(text(box_x + 16, top + 38, "is paired on the seed", size=12, fill=ACCENT, weight="700"))
    lines = [
        ("unpaired sd", "%.4f" % payload["unpaired_sd"], FAINT),
        ("paired sd", "%.4f" % payload["paired_sd"], TEAL),
        ("tighter by", "%.1fx" % payload["pairing_gain"], TEAL),
        ("seeds saved", "about %dx" % round(payload["pairing_gain"] ** 2), TEAL),
    ]
    for index, (label, value, colour) in enumerate(lines):
        y = top + 68 + index * 28
        parts.append(text(box_x + 16, y, label, size=11, fill=FAINT))
        parts.append(text(box_x + 220, y, value, size=12.5, fill=colour, anchor="end", weight="700"))
    parts.append(
        text(24, height - 20, "if you fork this and report a number, report the seed count with it.", size=11.5, fill=FAINT)
    )
    return write("precision.svg", "\n".join(parts), width, height)


def figure_architecture() -> str:
    width, height = 900, 486
    parts: List[str] = []
    heading(
        parts,
        "What runs where",
        "python decides what is true, C makes the hot loops fast, node decides what it looks like.",
        "the only thing crossing between them is a json file on disk.",
    )
    columns = [
        (24, "INGEST", ACCENT, [("data/loaders", "jsonl, csv, huggingface"), ("data/record", "content addressed digests"), ("data/versioning", "chained lineage"), ("data/splits", "stratified, disjoint")]),
        (320, "EXPERIMENT", ROSE, [("forge/", "5 attacks, exact budget"), ("models/", "surrogate, LoRA, ensemble"), ("train/engine", "sockets blocked"), ("evaluate/", "ASR, CDA, intervals")]),
        (616, "DEFEND", TEAL, [("defenses/", "8 detectors, rank fusion"), ("defenses/partition", "shard vote, certificate"), ("analysis/audit", "triage, permutation null"), ("analysis/potency", "predict before training")]),
    ]
    box_w = 260
    top = 104
    row_h = 52
    for x, title, colour, rows in columns:
        parts.append(panel(x, top, box_w, 40 + row_h * len(rows), colour))
        parts.append(rect(x + 16, top + 16, 24, 3, colour, rx=2))
        parts.append(text(x + 16, top + 30, title, size=12.5, fill=colour, weight="700"))
        for index, (name, note) in enumerate(rows):
            y = top + 48 + index * row_h
            parts.append(text(x + 16, y + 12, name, size=12, weight="600"))
            parts.append(text(x + 16, y + 28, note, size=11, fill=FAINT))
    mid = top + (40 + row_h * 4) / 2
    parts.append(arrow(24 + box_w + 6, mid, 320 - 6, mid))
    parts.append(arrow(320 + box_w + 6, mid, 616 - 6, mid))
    bottom = top + 40 + row_h * 4 + 26
    lanes = [
        (24, 260, "python 3.9+", "standard library only, zero dependencies", ACCENT),
        (320, 260, "C kernels", "featurize, gram stats, minhash, 9x to 75x", AMBER),
        (616, 260, "node viewer", "report json becomes one html file", TEAL),
    ]
    for x, w, title, note, colour in lanes:
        parts.append(panel(x, bottom, w, 54, colour, opacity=0.09, radius=8))
        parts.append(text(x + 16, bottom + 22, title, size=12, fill=colour, weight="700"))
        parts.append(text(x + 16, bottom + 40, note, size=11, fill=FAINT))
    parts.append(
        text(width / 2, height - 12, "every stage writes its digest into report.json, so any run replays exactly", size=11.5, fill=FAINT, anchor="middle")
    )
    return write("architecture.svg", "\n".join(parts), width, height)


def figure_threat_model() -> str:
    width, height = 900, 430
    parts: List[str] = []
    heading(
        parts,
        "Who controls what",
        "the attacker writes rows and nothing else. everything measured sits on the",
        "defender's side of the line.",
    )
    parts.append(panel(24, 96, 236, 250, DANGER, opacity=0.10))
    parts.append(text(40, 122, "ATTACKER", size=12.5, fill=DANGER, weight="700"))
    for index, item in enumerate(
        ["writes a bounded share of rows", "chooses their text", "chooses their label", "chooses their record id", "reads the public corpus"]
    ):
        parts.append(text(40, 150 + index * 23, "+  " + item, size=11.5))
    for index, item in enumerate(["cannot touch the eval set", "cannot see the seed", "cannot reach the network"]):
        parts.append(text(40, 282 + index * 21, "x  " + item, size=11.5, fill=FAINT))
    parts.append("<line x1='288' y1='96' x2='288' y2='346' stroke='%s' stroke-width='2' stroke-dasharray='6 5'/>" % AMBER)
    parts.append(text(288, 88, "trust boundary", size=11, fill=AMBER, anchor="middle", weight="700"))
    parts.append(panel(316, 96, 560, 250, TEAL, opacity=0.09))
    parts.append(text(336, 122, "DEFENDER, inside the sandbox", size=12.5, fill=TEAL, weight="700"))
    parts.append(
        "<rect x='330' y='136' width='534' height='86' rx='9' fill='none' stroke='%s' stroke-width='1.8' stroke-dasharray='5 4'/>" % AMBER
    )
    parts.append(text(338, 152, "network isolation wraps the whole run, not just training", size=10.5, fill=AMBER, weight="700"))
    stages = [("corpus", "bounded, local", ACCENT), ("forge", "exact budget", ROSE), ("train", "no sockets", AMBER), ("evaluate", "clean holdout", TEAL)]
    x = 342
    for index, (title, note, colour) in enumerate(stages):
        parts.append(panel(x, 160, 112, 52, colour, opacity=0.14, radius=8))
        parts.append(text(x + 11, 180, title, size=11.5, fill=colour, weight="700"))
        parts.append(text(x + 11, 198, note, size=10, fill=FAINT))
        if index < len(stages) - 1:
            parts.append(arrow(x + 115, 186, x + 122, 186))
        x += 124
    parts.append(panel(342, 234, 484, 44, ACCENT, opacity=0.13, radius=8))
    parts.append(text(354, 252, "output", size=11.5, fill=ACCENT, weight="700"))
    parts.append(text(354, 269, "control bytes neutralised before any terminal, report or html", size=10.5, fill=FAINT))
    parts.append(text(336, 300, "the sandbox is a tripwire, not a kernel boundary:", size=11.5, weight="600"))
    parts.append(text(336, 320, "it blocks sockets here, not in a child process or a C extension,", size=11, fill=FAINT))
    parts.append(text(336, 338, "so run untrusted corpora in a container with no network namespace.", size=11, fill=FAINT))
    parts.append(text(width / 2, height - 22, "not modelled: pretraining scale poison, federated training, weight tampering,", size=11, fill=FAINT, anchor="middle"))
    parts.append(text(width / 2, height - 6, "prompt injection at inference", size=11, fill=FAINT, anchor="middle"))
    return write("threat-model.svg", "\n".join(parts), width, height)


def figure_partition_mechanism() -> str:
    width, height = 900, 400
    parts: List[str] = []
    heading(
        parts,
        "How the shard vote bounds the damage",
        "a poisoned row lands in exactly one shard, so it can corrupt exactly one vote. nothing has to notice it.",
    )
    parts.append(panel(24, 96, 150, 120, ACCENT))
    parts.append(text(40, 124, "corpus", size=12.5, fill=ACCENT, weight="700"))
    for index in range(5):
        colour = DANGER if index == 1 else GRID
        parts.append(rect(40, 138 + index * 14, 100, 8, colour, rx=2, opacity=0.95 if index == 1 else 0.85))
    parts.append(text(40, 226, "one poisoned row", size=10.5, fill=DANGER, weight="600"))
    parts.append(text(196, 152, "sha256(uid) mod k", size=11, fill=AMBER, weight="700"))
    parts.append(arrow(190, 162, 320, 162, AMBER))
    shard_x = 336
    shard_w = 92
    for index in range(5):
        x = shard_x + index * (shard_w + 12)
        poisoned = index == 1
        colour = DANGER if poisoned else TEAL
        parts.append(panel(x, 100, shard_w, 74, colour, opacity=0.15, radius=8))
        parts.append(text(x + 10, 122, "shard %d" % (index + 1), size=11, fill=colour, weight="700"))
        parts.append(text(x + 10, 142, "model %d" % (index + 1), size=10.5, fill=FAINT))
        parts.append(text(x + 10, 160, "poisoned" if poisoned else "clean", size=10.5, fill=colour, weight="700"))
        parts.append(arrow(x + shard_w / 2, 178, x + shard_w / 2, 208))
    parts.append(panel(shard_x, 214, 5 * (shard_w + 12) - 12, 78, ACCENT, opacity=0.11))
    parts.append(text(shard_x + 16, 240, "plurality vote", size=12.5, fill=ACCENT, weight="700"))
    parts.append(text(shard_x + 16, 262, "allow 4    block 1", size=12, weight="700"))
    parts.append(text(shard_x + 16, 280, "winner leads by 3, so radius = (4 - 1 - 1) // 2 = 1", size=11, fill=FAINT))
    parts.append(panel(24, 306, 852, 62, TEAL, opacity=0.10, radius=8))
    parts.append(text(42, 330, "the certificate: if the winner leads the runner up by more than twice the corrupted shards,", size=11.5, weight="600"))
    parts.append(text(42, 352, "no attacker holding that many rows can change this answer, whatever those rows contain.", size=11.5, fill=TEAL, weight="700"))
    return write("partition-mechanism.svg", "\n".join(parts), width, height)


def figure_defense_layers() -> str:
    width, height = 900, 400
    parts: List[str] = []
    heading(
        parts,
        "Defense in depth",
        "each layer assumes the one before it failed. the last one does not depend on noticing anything at all.",
    )
    layers = [
        ("1  ingest bounds", "record, line, label and nesting ceilings; unique ids", "stops a corpus from being the exploit", ACCENT),
        ("2  eight detectors", "purity, contradiction, rarity, confusable, dynamics, spectral, clustering, neighbourhood", "AUC 0.92 to 0.98 for the best detector", ROSE),
        ("3  rank fusion and sanitising", "drop the top slice of the fused rank, then retrain", "ASR 0.855 to 0.123 at a 5% review budget", AMBER),
        ("4  bounded training", "class weight capped, per sample update capped", "one row can no longer dominate the model", TEAL),
        ("5  shard vote and certificate", "disjoint shards, plurality vote, per prediction radius", "ASR cut 64%, plus a floor no attack crosses", ACCENT),
    ]
    top = 88
    row_h = 58
    for index, (title, how, effect, colour) in enumerate(layers):
        y = top + index * row_h
        parts.append(panel(24, y, 852, 48, colour, opacity=0.11, radius=8))
        parts.append(rect(24, y, 5, 48, colour, rx=2, opacity=0.95))
        parts.append(text(44, y + 20, title, size=12, fill=colour, weight="700"))
        parts.append(text(44, y + 38, how, size=10.5, fill=FAINT))
        parts.append(text(560, y + 20, effect, size=11, weight="600"))
        if index < len(layers) - 1:
            parts.append(arrow(450, y + 50, 450, y + row_h - 2))
    parts.append(
        text(width / 2, height - 14, "layers 1 to 3 have to be right about the data. layers 4 and 5 hold whether or not anything was detected.", size=11.5, fill=FAINT, anchor="middle")
    )
    return write("defense-layers.svg", "\n".join(parts), width, height)


FIGURES = (
    figure_headline,
    figure_pipeline,
    figure_architecture,
    figure_threat_model,
    figure_partition_mechanism,
    figure_defense_layers,
    figure_dose_response,
    figure_selection,
    figure_detectors,
    figure_evasion,
    figure_stealth,
    figure_partition,
    figure_audit,
    figure_precision,
)

REQUIRED = ("dose_response", "selection", "detectors", "stealth", "partition", "audit", "evasion", "precision")


def main() -> int:
    if not os.path.isdir(DATA):
        sys.stderr.write("run scripts/experiments.py first, no data in %s\n" % DATA)
        return 1
    missing = [name for name in REQUIRED if not os.path.exists(os.path.join(DATA, "%s.json" % name))]
    if missing:
        sys.stderr.write("missing study data for %s, run: python scripts/experiments.py\n" % ", ".join(missing))
        return 1
    made: List[str] = []
    for theme in ("light", "dark"):
        use_theme(theme)
        for builder in FIGURES:
            made.append(builder())
    for path in made:
        sys.stdout.write("%s\n" % os.path.relpath(path, ROOT))
    sys.stdout.write("%d files across two themes\n" % len(made))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
